### ISSUE TITLE
(Documentation) Instructions for udev rule on linux

### ISSUE THREAD

**Issue by databoose** [sourcebox/dfu-buddy#5]
I am quite stumped here, i have ran the dfu buddy appimage on linux both with and without root, and i cannot find my USB-C bluetooth device listed.

![image](https://github.com/sourcebox/dfu-buddy/assets/7876395/11b6938a-954c-43ce-a27e-61b123ba7e32)

As stated here within the readme, it says that i need to set up the udev rules correctly, but as far as i can tell in the documentation no instructions for how to do this are shown.

Any ideas? Thanks.

**Comment by sourcebox** [comment]
Linux udev rules are a security feature of the operating system and not related to a certain application like DFU Buddy. Therefore, you have to refer to some general documentaion about them, e.g. https://wiki.archlinux.org/title/udev

The udev rules include the vendor and product id of the DFU device, so you have to find them out first. In case of an STM32-based device, have a look here: https://github.com/wiieva/dfu-util/blob/master/doc/40-dfuse.rules

If your device is not based on an STM32, then DFU Buddy will maybe not work. Try to use the command line `dfu-util` in that case. The udev rules are also required then.

**Comment by sourcebox** [comment]
Also make sure that your device is in DFU mode before starting DFU Buddy.

**Comment by databoose** [comment]
> Linux udev rules are a security feature of the operating system and not related to a certain application like DFU Buddy. Therefore, you have to refer to some general documentaion about them, e.g. https://wiki.archlinux.org/title/udev
> 
> The udev rules include the vendor and product id of the DFU device, so you have to find them out first. In case of an STM32-based device, have a look here: https://github.com/wiieva/dfu-util/blob/master/doc/40-dfuse.rules
> 
> If your device is not based on an STM32, then DFU Buddy will maybe not work. Try to use the command line `dfu-util` in that case. The udev rules are also required then.

Thanks, i appreciate the help, and apologies for the extremely late reply, i will be closing this issue.
